CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID NUMBER PRIMARY KEY,
    DEPARTMENT_ID NUMBER NOT NULL,
    CHIEF_ID NUMBER UNIQUE,
    NAME TEXT NOT NULL,
    SALARY NUMBER NOT NULL
);
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    ID NUMBER PRIMARY KEY ,
    NAME TEXT NOT NULL
);
